### PR TITLE
support switching of network overlay mode

### PR DESCRIPTION
**Pull request by DockToFuture**
**How to categorize this PR?**

/area networking
/kind enhancement
/platform gcp

**What this PR does / why we need it**:
Overlay networks for newly created calico shoot clusters are dropped now by default. To keep the overlay network `networking.providerConfig.overlay.enabled: true` needs to be set explicitly in the shoot spec.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Overlay networks for newly created calico shoot clusters are dropped now by default.  To keep the overlay network `networking.providerConfig.overlay.enabled: true` needs to be set explicitly in the shoot spec.
```

### CODE REVIEW

**Comment by DockToFuture** [comment]
This PR is on hold to until a new calico release was created with https://github.com/gardener/gardener-extension-networking-calico/pull/215.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
