### PR TITLE
Replace terraformer's helm chart with go templates

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind cleanup
/platform gcp

**What this PR does / why we need it**:
Replace infrastructure helm chart with native go templates

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Replace infrastructure's terraform helm chart with native go templates. 
```

### CODE REVIEW

**Comment by prashanth26** [comment]
Hi @kon-angelo ,

Thanks for these changes. 
/assign

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by prashanth26 — COMMENTED** [review]
/lgtm

**Pull request merged**
