### PR TITLE
Switch to kaniko oci builder

### PR DESCRIPTION
**Pull request by ialidzhikov**
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/281

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
Hold until the issue for image pull from containerd is resolved - ref https://github.com/gardener/replica-reloader/issues/6.

/hold

**Comment by ialidzhikov** [comment]
Unhold as the above issue is resolved.

/unhold

**Comment by ialidzhikov** [comment]
Can someone from the repository admins help making the `concourse-ci/build_oci_image_gardener-extension-provider-gcp` and `concourse-ci/build_oci_image_gardener-extension-admission-gcp ` checks required (and `concourse-ci/publish` is no longer required)? Thanks in advance!

**Comment by prashanth26** [comment]
>Can someone from the repository admins help making the concourse-ci/build_oci_image_gardener-extension-provider-gcp and concourse-ci/build_oci_image_gardener-extension-admission-gcp checks required (and concourse-ci/publish is no longer required)? Thanks in advance!

I am on the `provider-gcp` maintainers list. However, even I don't have admin access on the repository. @DockToFuture do you have this access?

**Pull request merged**
