### PR TITLE
Implement Migrate and Restore

### PR DESCRIPTION
**Pull request by vlvasilev**
**What this PR does / why we need it**:
This PR implements Migrate and Restore function on the Infrastructure Actuator according to PR [#2167](https://github.com/gardener/gardener/pull/2167).
Migrate deletes the two ConfigMaps which store the Terraform configuration and state. It also deletes the Secret which stores the Terraform variables.
Restore reads the state from Insfrastrucure.Status.State and deploys it in the ConfigMap which store the Terraform state.
**Which issue(s) this PR fixes**:
Fixes [#1631](https://github.com/gardener/gardener/issues/1631)

**Special notes for your reviewer**:

**Release note**:

```improvement operator
implement Migrate and Restore functionality
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Converted to a draft PR as its dependencies are not yet resolved. Please mark as 'ready for review' once they are resolved.

**Comment by vlvasilev** [comment]
The PR is tested. But make verify fails with:
```
test/e2e/networkpolicies/networkpolicy_test.go:35:2: SA1019: package github.com/gardener/gardener/test/integration/framework is deprecated: this is the deprecated gardener testframework. Use gardener/test/framework instead  (staticcheck)
        gardenerframework "github.com/gardener/gardener/test/integration/framework"
        ^

```
After merging the [2167](https://github.com/gardener/gardener/pull/2167)
I will remove 
`github.com/gardener/gardener => github.com/vlvasilev/gardener v0.0.0-20200423121540-5ab2b6c74abe` 

At the moment to test it one must only fetch the PR

**Comment by rfranzke** [comment]
See https://github.com/gardener/gardener-extension-provider-alicloud/pull/52#issuecomment-618406211

**Comment by rfranzke** [comment]
See https://github.com/gardener/gardener-extension-provider-alicloud/pull/52#issuecomment-618406211

**Pull request merged**
