### PR TITLE
Vendor gardener/gardener@v1.10.0

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement
/priority normal
/platform gcp

**What this PR does / why we need it**:
Vendor gardener/gardener@v1.10.0

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

**Review by timebertt — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Review by DockToFuture — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Good suggestion @DockToFuture, I would go ahead as is for now and update these versions once we revendor g/g@v1.11 which will force us to upgrade to the 1.18 version of the Kubernetes dependencies. 👍

**Pull request merged**
