### PR TITLE
Vendor gardener/gardener@v1.25.0

### PR DESCRIPTION
**Pull request by rfranzke**
**How to categorize this PR?**

/area open-source
/kind enhancement
/platform gcp

**What this PR does / why we need it**:
Vendor gardener/gardener@v1.25.0

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Review by ialidzhikov — COMMENTED** [review]
According to @timebertt , `DeepCopy`s can be now removed from the infrastructure test - ref https://github.com/gardener/gardener-extension-provider-gcp/pull/280#issuecomment-857653041.

**Comment by rfranzke** [comment]
Nice catch @ialidzhikov, thanks!
/squash

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Though, actually, we agreed to only release extensions with vendoring "tagged versions" of g/g, so probably it should go in?

**Comment by ialidzhikov** [comment]
> Though, actually, we agreed to only release extensions with vendoring "tagged versions" of g/g, so probably it should go in?

Agree.

/unhold

**Review by ialidzhikov — APPROVED** [review]
/lgtm

**Pull request merged**
