### PR TITLE
disable snat for non-overlay shoots

### PR DESCRIPTION
**Pull request by DockToFuture**
**How to categorize this PR?**

/area networking
/kind enhancement
/platform gcp

**What this PR does / why we need it**:
After the default behaviour in the calico extension was changed to use SNAT to the upstream dns server by default, this PR reverses the behaviour for gcp shoot cluster and disables SNAT to the upstream dns server in the non-overlay case.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Disable SNAT to the upstream dns server for non-overlay shoot cluster.
```

### CODE REVIEW

**Comment by DockToFuture** [comment]
//cc: @ScheererJ

**Review by ScheererJ — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
