### PR TITLE
[GEP-18] Revendor `gardener/gardener@v1.45`, cleanup token projection artefacts, adapt to new secrets manager

### PR DESCRIPTION
**Pull request by BeckerMax**
**How to categorize this PR?**

/area security
/kind enhancement
/platform aws

**What this PR does / why we need it**:

This PR used the AWS adaption (https://github.com/gardener/gardener-extension-provider-aws/pull/538) as a blueprint and adapted it to GCP.
Special thanks to @timebertt for providing a well-readable PR and a nice description of the adaption needed in the extensions in https://github.com/gardener/gardener/pull/5803 .

Details:

- Vendors g/g and adapts to all breaking changes introduced by https://github.com/gardener/gardener/pull/5803
- Cleans up a lot of migration code around moving to short-lived serviceaccount tokens introduced with #368
- Adapts this extension to the new secrets manager, which makes it ready for supporting the shoot CA rotation feature

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/3292

**Special notes for your reviewer**:

Use the dedicated commits, otherwise this PR is pretty much unreviewable.

**Release note**:

```breaking operator
This extension is only compatible with Gardener versions `>= v1.37`.
```
```feature operator
This extension is prepared to support the Shoot CA rotation feature ([GEP-18](https://github.com/gardener/gardener/issues/3292)).
```

### CODE REVIEW

**Comment by rfranzke** [comment]
Very nice, the changes look great to me.
Can you also add another commit like in https://github.com/gardener/gardener-extension-provider-vsphere/pull/230/commits/b5fc894aa0cf9745678160ca63b6f4b57e734b48?

**Review by rfranzke — DISMISSED** [review]
/lgtm

**Review by timebertt — APPROVED** [review]
Thank you!
/lgtm

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
