### PR TITLE
update test definitions

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind cleanup
/platform gcp

**What this PR does / why we need it**:
Update the test definitions to the latest golang.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by shafeeqes** [comment]
> Testrun: [e2e-dg2p9](https://tm.gardener.cloud/testrun/default/e2e-dg2p9) Workflow: e2e-dg2p9-wf Phase: Failed
> 
> +---------------------+---------------------+-----------+----------+
> |        NAME         |        STEP         |   PHASE   | DURATION |
> +---------------------+---------------------+-----------+----------+
> | infrastructure-test | infrastructure-test | Failed    | 6m38s    |
> | bastion-test        | bastion-test        | Succeeded | 8m42s    |
> +---------------------+---------------------+-----------+----------+

Fails with
```
  STEP: wait until infrastructure is deleted 10/10/22 13:56:30.907
    1.6654101909078937e+09      ERROR   infrastructure-test     Object did not get deleted yet  {"error": "Error reconciling infrastructure: failed to apply the terrafo
rm config: failed to deploy the Terraformer pod with .meta.generateName \"infrastructure.infra.tf-apply-\": pods \"infrastructure.infra.tf-apply-\" is forbidden: no Pri
orityClass with name gardener-system-300 was found"}
```

**Review by dkistner — APPROVED** [review]
/lgtm

**Pull request merged**
