### PR TITLE
Add arm support

### PR DESCRIPTION
**Pull request by acumino**
**How to categorize this PR?**

/area delivery
/kind enhancement
/platform gcp

**What this PR does / why we need it**:
This PR Adds a new `architecture` field in `WorkerStatus` and `CloudProfileConfig` to support specifying architecture.
 - `CloudProfileConfig` now supports a new field `.machineImages[].machineImageVersion[].architecture`. It specifies the supported CPU architecture of the given machine image.
 - `WorkerStatus` now supports a new field `.machineImage[].architecture`. It specifies the supported CPU architecture of the given worker pool.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/backlog/issues/19

**Special notes for your reviewer**:

**Release note**:

```feature operator
`CloudProfileConfig` now supports a new field `.machineImages[].machineImageVersion[].architecture`. It specifies the supported CPU architecture of the given machine image.
```
```feature operator
`WorkerStatus` now supports a new field `.machineImage[].architecture`. It specifies the supported CPU architecture of the given worker pool.
```

### CODE REVIEW

**Review by dkistner — APPROVED** [review]
/lgtm

**Comment by dkistner** [comment]
I guess we can safely move on as the `amd64` is defaulted as architecture for all existing entries in the cloudprofile and the machine status?

**Comment by acumino** [comment]
/invite @ialidzhikov I have tested the changes. We can go ahead and merge this.

**Comment by rfranzke** [comment]
/uninvite @rfranzke 
@dkistner @kon-angelo please go ahead without me

**Review by dkistner — APPROVED** [review]

**Pull request merged**
